name: elixir
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9.1-slim
    steps:
      - uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install build-essential -y
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Static Analysis
        run: mix credo
      - name: Tests
        run: mix test
